---
- name: Agregar monitoreo de ping en servidores_lnx.dat
  lineinfile:
    path: /home/monitor/sh_ping/dat/servidores_lnx.dat
    line: "{{ansible_default_ipv4['address']}}"
  delegate_to: 10.31.32.20

- name: Agregar monitoreo de ping en 
  lineinfile:
    path: "/home/monitor/sh_ping/dat/{{ansible_default_ipv4['address']}}"
    line: "{{ansible_hostname}}"
    create: yes
  delegate_to: 10.31.32.20
