  - name: ACTUALIZAR POLKIT RHEL  
    yum:
      name: "{{ packages }}"
      state: latest
      update_only: yes
      update_cache: yes
      disable_plugin: '*'
      disablerepo: '*'
      enablerepo: "{{ repos }}"
