---
- name: '[ ACTUALIZAR SO ]'
  yum:
    name: "*"
    state: latest
    disable_plugin: '*'
    disablerepo: '*'
    enablerepo: bastionREPO,bastionREPOBO,bastionREPOAS

- name: '[ REINICIAR UNA MAQUINA ]'
  reboot:
    msg: "Reinicio realizado mediante Ansible"
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
