---
- name: '[ DESACTIVAR NETWORKMANAGER ]'
  systemd:
    name: NetworkManager
    state: stopped
    enabled: no
  when:
    - ansible_facts['distribution_major_version'] != "8"

- name: '[ DESACTIVAR FIREWALLD ]'
  systemd:
    name: firewalld 
    state: stopped
    enabled: no

- name: '[ DESACTIVAR SELINUX ]'
  selinux:
    state: disabled

- name: '[ CAMBIAR TARGET A MULTI-USER ]'
  command: systemctl set-default multi-user.target

- name: '[ DESHABILITAR ZEROCONF ]'
  lineinfile:
    path: /etc/sysconfig/network
    regexp: '^NOZEROCONF='
    line: NOZEROCONF=yes

